- name: Add allow rule for 3306 to firewall
  firewalld: zone=public port=3306/tcp permanent=true state=enabled
  notify:
  - Restart the mariadb service

- name: Create a new database with name 'demo_loadbanlancer_wp_gsviec'
  mysql_db:
    login_password: "{{ mysq_password_root }}"
    login_user: root
    name: "{{ mariadb_database }}"
    state: present


# Copy database dump file to remote host and restore it to database 'my_db'
- name: Copy database dump file
  copy:
    src: "files/{{ mariadb_file}}"
    dest: /tmp/
- name: Restore database
  mysql_db:
    name: "{{ mariadb_database }}"
    state: import
    target: "/tmp/{{ mariadb_file }}"