- name: Add allow rule for 3306 to firewall
  firewalld: zone=public port=3306/tcp permanent=true state=enabled
- name: Configure mariadb for easy access as root user
  template: src=my.cnf.j2 dest=/etc/my.cnf owner=root group=root mode=0644

- name: ensure anonymous users are not in the database
  mysql_user: name='' host=* state=absent

- name: Default User
  mysql_user: name={{ mariadb_admin_user }} password={{ mariadb_admin_password }} host=% priv=*.*:ALL,GRANT state=present

- name: remove the test database
  mysql_db: name=test state=absent
  notify:
    - Restart the mariadb service

- name: Set the root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mariadb_password_root }} priv=*.*:ALL,GRANT
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  when: ansible_hostname != 'localhost'

- name: Create a new database with name {{ mariadb_database }}
  mysql_db:
    login_user: root
    login_password: "{{ mariadb_password_root }}"
    name: "{{ mariadb_database }}"
    state: present

# Copy database dump file to remote host and restore it to database 'my_db'
- name: Copy database dump file
  copy:
    src: "files/{{ mariadb_file}}"
    dest: /tmp/
- name: Restore database
  mysql_db:
    login_user: root
    login_password: "{{ mariadb_password_root }}"
    name: "{{ mariadb_database }}"
    state: import
    target: "/tmp/{{ mariadb_file }}"
  ignore_errors: yes